### ISSUE TITLE
App crash while calling connectNode() function 

### ISSUE THREAD

**Issue by Chandra-Sekhar-Kotlin** [TronLink/tronlink-android-core#4]
Here is the error: 
```
FATAL EXCEPTION: main (Ask Gemini)
                
                 java.lang.NoSuchMethodError: No static method internalBuildGeneratedFileFrom([Ljava/lang/String;[Lcom/google/protobuf/Descriptors$FileDescriptor;Lcom/google/protobuf/Descriptors$FileDescriptor$InternalDescriptorAssigner;)V in class Lcom/google/protobuf/Descriptors$FileDescriptor; or its super classes (declaration of 'com.google.protobuf.Descriptors$FileDescriptor' appears in /data/app/~~6CUbR39Bf2KdU-6tbIOt6Q==/.app-130k-wgJKB-chLLrfOBWPw==/base.apk!classes20.dex)
                 	at org.tron.protos.Discover.<clinit>(Discover.java:4588)
                 	at org.tron.protos.Discover.getDescriptor(Discover.java:4556)
                 	at org.tron.protos.Protocol.<clinit>(Unknown Source:27)
                 	at org.tron.protos.Protocol.access$24100(Protocol.java:6)
                 	at org.tron.protos.Protocol$Account$AssetDefaultEntryHolder.<clinit>(Protocol.java:15607)
                 	at org.tron.protos.Protocol$Account$Builder.internalGetAsset(Protocol.java:18523)
                 	at org.tron.protos.Protocol$Account$Builder.buildPartial(Protocol.java:17610)
                 	at org.tron.protos.Protocol$Account$Builder.build(Protocol.java:17585)
                 	at domain.usecase.transaction.TronTransactionUseCase.connectNode(TronTransactionUseCase.kt:85)
                 	at domain.usecase.transaction.TronTransactionUseCase.initiate(TronTransactionUseCase.kt:70)
                 	at presentation.ui.screens.transaction.send.sendTokenDetails.SendTokenDetailsViewModel$sendAmount$1.invokeSuspend(SendTokenDetailsViewModel.kt:109)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:363)
                 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:274)
                 	at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletion(Scopes.kt:23)
                 	at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:937)
                 	at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:22)
                 	at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1156)
                 	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1492)
                 	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:322)
                 	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:239)
                 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:907)
                 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:864)
                 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:829)
                 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:97)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7872)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@66c5db3, Dispatchers.Main.immediate]
```

 I have followed [this code](https://github.com/TronLink/tronlink-android-core/blob/main/core/src/test/java/org/tron/TransactionCoreUnitTest.java) But still this issue came up again and again. 
 
 Here is my [build.gradle.kts](https://gist.github.com/Chandra-Sekhar-Kotlin/8afa910354c4d08e3b7aab97c8f99578) for reference. 
 
 Can any maintainer please take a look? 
@tronlinkdev @slo-w @Tain-tl @victronlink

**Comment by Chandra-Sekhar-Kotlin** [comment]
Hey I found the solution. 
Taking the protobuf out of android block to the root solved the problem.
